# BungeePlaytimeTracker configuration

# MySQL or MariaDB configuration
database:
  host: localhost
  port: 3306
  database: bungee
  username: root
  password: password

# Reload players on startup, if this enabled,
# the plugin will take a while to load and will disable the setting afterward
reload-players: false
