# BungeePlaytimeTracker configuration
language: en
print_session_update: true

# MySQL or MariaDB configuration
database:
  host: localhost
  port: 3306
  database: bungee
  username: root
  password: password

# Reload players on startup, if this enabled,
# the plugin will take a while to load and will disable the setting afterward
reload-players: false

# Select servers for exclude in playtime calculation
# If you exclude a server later, then you need to reload the players above for the change to take effect for all users.
exclude-servers: []
