name: BungeePlaytimeTracker
version: '1.0'
main: de.midevelopment.minecraft.bungeePlaytimeTracker.spigot.BungeePlaytimeTrackerSpigot
author: Miku
description: Tracks the playtime of players inside the BungeeCord network.

depend:
  - PlaceholderAPI
